### ISSUE TITLE
[ETHEREUM-CONTRACTS] building fails

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/protocol-monorepo#1741]
```
$ IS_HARDHAT=true npx hardhat compile
An unexpected error occurred:

Error: Cannot find module './core'
Require stack:
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/lib/is-core.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/lib/async.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/index.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/solidity/resolver.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/builtin-tasks/compile.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/core/config/config-loading.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/cli/cli.js
- /home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/cli/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/lib/is-core.js:1:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .js] (/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/lib/is-core.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/lib/async.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/node_modules/resolve/index.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/solidity/resolver.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/builtin-tasks/compile.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/core/tasks/builtin-tasks.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/core/config/config-loading.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/cli/cli.js',
    '/home/dev/protocol-monorepo/branches/gda-fixes/node_modules/hardhat/internal/cli/bootstrap.js'
  ]
}
```

This is after a fresh checkout (to be more precise: fresh checkout using git worktree), using a nix env as defined by `flake.nix`.
It seems to not happen on CI, meaning something isn't as deterministic as we're assuming.

**Comment by d10r** [comment]
now having the same on dev branch

**Comment by d10r** [comment]
The issue seems to be with the resolve npm package.
For some reason, sometimes a file is missing.

Working env:
```
didi@P1G4:~/src/sf/protocol-monorepo/b/gda$ ll node_modules/hardhat/node_modules/resolve/lib/
total 52
drwxrwxr-x 2 didi didi  4096 Dez 21 13:11 ./
drwxrwxr-x 5 didi didi  4096 Aug 23 20:42 ../
-rw-r--r-- 1 didi didi 10456 Aug  3  2022 async.js
-rw-r--r-- 1 didi didi   354 Aug  3  2022 caller.js
-rw-r--r-- 1 didi didi  1662 Aug  3  2022 core.js
-rw-r--r-- 1 didi didi  2247 Aug  3  2022 core.json
-rw-r--r-- 1 didi didi   130 Aug  3  2022 is-core.js
-rw-r--r-- 1 didi didi  1256 Aug  3  2022 node-modules-paths.js
-rw-r--r-- 1 didi didi   348 Aug  3  2022 normalize-options.js
-rw-r--r-- 1 didi didi  6267 Aug  3  2022 sync.js
```

failing env:
```
dev@buck2:~/protocol-monorepo-tmp$ ll /home/dev/protocol-monorepo-tmp/node_modules/hardhat/node_modules/resolve/lib/
total 44
drwxr-xr-x 2 dev dev  4096 Dec 21 12:11 ./
drwxr-xr-x 5 dev dev  4096 Dec 21 12:06 ../
-rw-r--r-- 1 dev dev 10456 May  9  2022 async.js
-rw-r--r-- 1 dev dev   354 May  9  2022 caller.js
-rw-r--r-- 1 dev dev   130 May  9  2022 is-core.js
-rw-r--r-- 1 dev dev  1256 May  9  2022 node-modules-paths.js
-rw-r--r-- 1 dev dev   348 May  9  2022 normalize-options.js
-rw-r--r-- 1 dev dev  6267 May  9  2022 sync.js
```

The package.json is identical on both systems:
```
didi@P1G4:~/src/sf/protocol-monorepo/b/gda$ md5sum node_modules/hardhat/node_modules/resolve/package.json 
32a1b5e1e08fa2264cf703dc0c500708  node_modules/hardhat/node_modules/resolve/package.json
...
dev@buck2:~/protocol-monorepo-tmp$ md5sum /home/dev/protocol-monorepo-tmp/node_modules/hardhat/node_modules/resolve/package.json
32a1b5e1e08fa2264cf703dc0c500708  /home/dev/protocol-monorepo-tmp/node_modules/hardhat/node_modules/resolve/package.json
```

I tried both using nix and not using it, didn't make a difference.
Also verified that it indeed also happens after a fresh checkout.

**Comment by d10r** [comment]
The resolve package also exists on the global level, at node_modules/resolve.
Here again, the failing system doesn't have all files in the lib folder the working one has.
package.json again is the same on both systems, but it's different from the version of the package nested in the hardhat package.

**Comment by d10r** [comment]
drilling a bit more...

on the working system:
```
$ cat node_modules/resolve/package.json | jq ".version"
"1.22.1"

$ ls node_modules/resolve/lib/
async.js  caller.js  core.js  core.json  homedir.js  is-core.js  node-modules-paths.js  normalize-options.js  sync.js
```

This matches the files in https://github.com/browserify/resolve/tree/v1.22.1/lib

on the failing system:
```
$ cat node_modules/resolve/package.json | jq ".version"
"1.22.1"
$ ls node_modules/resolve/lib/
async.js  caller.js  homedir.js  is-core.js  node-modules-paths.js  normalize-options.js  sync.js
```

`core.js` and `core.json` are missing.

On the working system I retried, with a clean dev branch, using nix. Still the same result.
Both systems have Ubuntu 22.04.3 LTS running.

**Comment by d10r** [comment]
On the failing system, created a new npm proj, did `npm install resolve@1.22.1`.
Now the missing files are included.

I don't currently have more ideas for how to nail it down.
Doesn't make sense to me that despite using a nix environment and a yarn lockfile, we can get this diverging result on the same OS, same CPU arch.

**Comment by d10r** [comment]
still failing after merging gda to dev

**Comment by hellwolf** [comment]
I have fixed the source of the issue per https://github.com/foundry-rs/foundry/issues/6732

The monorepo is temporarily fixed to a old foundry.nix commit. And I will update the flake.nix of monorepo soon.

Closing

**Comment by d10r** [comment]
I still have this with current dev branch (commit c7c06bd65a21d5e09f27967e6251d0e821de4854)

**Comment by d10r** [comment]
this turned out to be a package caching issue.
After running `yarn cache clean`, the problem disappeared.
